### ISSUE TITLE
What should I do if I use lon and lat as input x and y.

### ISSUE THREAD

**Issue by DayuanJiang** [paulbrodersen/inverse-distance-weighting-interpolation#1]
Thanks for creating this library.
But it only work for the case that the x and y coordinates are interpreted as on a plane (‘euclidean’) .
What should I do if I use lon and lat as input x and y?

**Comment by paulbrodersen** [comment]
As I use `scipy.spatial.cKDTree` to compute the distances, only distance functions that are p-norms are supported. Geographical data is, in principle, out of scope. 

*However*, keep in mind that only the distances to the nearest neighbours are ever used in the interpolation. If your data set is not too sparse, those neighbours may be close enough such that the error due to the curvature of the earth can be neglected. 

Also, even if that is not the case, all that you are doing "wrong" is using a slightly shallower weighting function. The expectation of the mean of the variable that you are interpolating should not be affected. The only effect should be that the smoothness of the estimate will be slightly larger (as you are underestimating the distance of far away points). 

Another way of looking at this problem is that the choice of basis function in density estimation (i.e. the function that you use to weigh different contributing data points in your local estimate) is always a trade-off between precision and accuracy, and hence subjective (or at the very least context dependent). In principle, I hence don't see a problem if you effectively make a small change to the basis function by using euclidean distances for geographical data.   

Hope that helps. I will close the issue as it is out-of-scope, but I will have a look at this thread tomorrow or the day after to see if you have any follow-up questions..
